#include: package:flutter_lints/flutter.yaml
include: package:lint/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    require_trailing_commas: ignore

linter:
  rules:
    - avoid_returning_null
    - always_require_non_null_named_parameters
    - null_check_on_nullable_type_parameter
