name: nb_navigation_flutter
description: A Flutter plugin for Nextbillion.ai Navigation SDK, providing turn-by-turn navigation.
version: 3.0.0-dev.3
homepage: https://docs.nextbillion.ai/routing/flutter-navigation-sdk
repository: https://github.com/nextbillion-ai/nextbillion-navigation-flutter

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  nb_maps_flutter:
    git:
      url: https://github.com/nextbillion-ai/nextbillion-maps-flutter.git
      ref: update/map_styles

  plugin_platform_interface: ^2.0.2

dev_dependencies:
  build_runner: ^2.1.5
  flutter_driver:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.6.1
  mockito: ^5.0.17
  provider: ^6.1.2
  test: ^1.24.9

flutter:
  plugin:
    platforms:
      android:
        package: ai.nextbillion.navigation.nb_navigation_flutter
        pluginClass: NbNavigationFlutterPlugin
      ios:
        pluginClass: NbNavigationFlutterPlugin

  assets:
    - assets/ic_route_destination.png
    - assets/ic_route_origin.png
